#
# This file was auto-generated by civicrm-install.sh, Mon Dec 21 16:43:35 GMT 2015
#
$path = "/var/local/brisskit/drupal/site/civicrm/sites/all/modules/civicrm";

#crm defined constant to config dir -> deals with symlinks
define("CIVICRM_CONFDIR","/var/local/brisskit/drupal/site/civicrm/sites/default");

set_include_path("$path/drupal" . PATH_SEPARATOR . $path . PATH_SEPARATOR . $path."/packages".PATH_SEPARATOR."/var/local/brisskit/drupal/site/civicrm/sites/default");
