<?php
/*****************************************************************************************
**  REDCap is only available through a license agreement with Vanderbilt University
******************************************************************************************/

require_once dirname(dirname(__FILE__)) . "/Config/init_global.php";
require_once APP_PATH_CLASSES . 'Message.php';

//If user is not a super user, go back to Home page
if (!$super_user) { redirect(APP_PATH_WEBROOT); exit; }

if (isset($_POST['url']))
{
	$message = '
		<html>
		<body style="font-family:Arial;font-size:10pt;">
		[This message was automatically generated by REDCap at ANOTHER institution]<br><br>
		<a href="'.$_POST['url'].'">Click this link</a> to manually report the REDCap stats for <b>'.$institution.'</b>.<br><br>
		Reported by <b>'.$user_firstname.' '.$user_lastname.'</b> ('.$user_email.')
		</body>
		</html>';
	$email = new Message();
	$email->setFrom('rob.taylor@vanderbilt.edu');
	$email->setTo('rob.taylor@vanderbilt.edu');
	$email->setSubject('REDCap site stats (alternative report method)');
	$email->setBody($message);
	if ($email->send())
	{
		redirect(APP_PATH_WEBROOT . "ControlCenter/index.php?sentstats=" . $_POST['sentstats'] . "&alternative=1");
		exit;
	}	
}

redirect(APP_PATH_WEBROOT . "ControlCenter/index.php");